### ISSUE TITLE
Counts of parents and children

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [joshsh/smsn#33]
I believe navigating would be easier if a column showed the number of parents for each node, and another the number of children. In particular, nodes with |parents| > 1 are special; I wish they jumped out at me.

(A further dream along these lines would be a memory footprint -- an indicator of the total number of nodes descended from a given node. It would be computationally expensive, and would take up more screen space, so it would be an unnatural default state for the app -- but it seems like a natural option to have. It could help someone, for instance, avoid misplacing a large quantity of data when they put it under an obscure branch. (Freeplane has the same problem. In a tree with four branches, one branch might have a hundred thousand descendants, and the others just a few; nothing informs the user of the difference.))

**Comment by joshsh** [comment]
This is done.  Let's keep the more in-depth node metrics in mind for future development.
