### ISSUE TITLE
bug ? change view-depth of {root view, search view} => switch buffer

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [joshsh/smsn#37]
When I'm viewing all roots (Cc Cf), and in move-mode, if I press "h 2" (to set the view-depth to 2) it bounces me to a different buffer.

Josh suggests in email it applies to search results more generally.

**Comment by joshsh** [comment]
Fixed in https://github.com/joshsh/brain-mode/commit/6e2d3da0594670a8f576a988e9d17e1b4d776c32
